name: environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - ipywidgets
  - pandas
  - wordcloud
  - plotly
  - seaborn
  - bqplot
  - matplotlib.pyplot
  - datetime
  - plotly.graph_objects
  - pyplot
  - plotly.subplots
  - plotly.graph_objects
  - matplotlib.colors
  - seaborn
  - plotly.express
  
